CREATE TABLE tool_category (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(32) COLLATE utf8mb4_0900_as_cs NOT NULL,
    name VARCHAR(64) NOT NULL,
    icon VARCHAR(128) NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tool_category_code (code),
    KEY idx_tool_category_status_sort (status, sort_order, id),
    CONSTRAINT ck_tool_category_status CHECK (status IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tool_definition (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tool_code VARCHAR(64) COLLATE utf8mb4_0900_as_cs NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    category_id BIGINT NOT NULL,
    icon VARCHAR(128) NULL,
    keywords_json JSON NOT NULL DEFAULT (JSON_ARRAY()),
    mode VARCHAR(16) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT 'LOCAL',
    version INT NOT NULL DEFAULT 1,
    status VARCHAR(16) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT 'ENABLED',
    sort_order INT NOT NULL DEFAULT 0,
    is_featured TINYINT NOT NULL DEFAULT 0,
    requires_login TINYINT NOT NULL DEFAULT 0,
    config_json JSON NOT NULL DEFAULT (JSON_OBJECT()),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tool_definition_code (tool_code),
    KEY idx_tool_definition_category_status_sort (category_id, status, sort_order, id),
    KEY idx_tool_definition_status_sort (status, sort_order, id),
    KEY idx_tool_definition_featured_sort (status, is_featured, sort_order, id),
    CONSTRAINT fk_tool_definition_category FOREIGN KEY (category_id) REFERENCES tool_category (id),
    CONSTRAINT ck_tool_definition_mode CHECK (mode IN ('LOCAL', 'SERVER', 'HYBRID')),
    CONSTRAINT ck_tool_definition_status CHECK (status IN ('ENABLED', 'DISABLED', 'MAINTENANCE')),
    CONSTRAINT ck_tool_definition_version CHECK (version >= 1),
    CONSTRAINT ck_tool_definition_featured CHECK (is_featured IN (0, 1)),
    CONSTRAINT ck_tool_definition_login CHECK (requires_login IN (0, 1)),
    CONSTRAINT ck_tool_definition_keywords CHECK (JSON_TYPE(keywords_json) = 'ARRAY'),
    CONSTRAINT ck_tool_definition_config CHECK (JSON_TYPE(config_json) = 'OBJECT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
