package com.cangshuo.toolbox.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// The shared light palette comes from the Stitch catalog, calculator and settings references.
internal val ToolboxLightColors = lightColorScheme(
    primary = Color(0xFF003FB1),
    onPrimary = Color.White,
    primaryContainer = Color(0xFF1A56DB),
    onPrimaryContainer = Color(0xFFD4DCFF),
    inversePrimary = Color(0xFFB5C4FF),
    secondary = Color(0xFF515F74),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFD5E3FC),
    onSecondaryContainer = Color(0xFF57657A),
    tertiary = Color(0xFF00544C),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFF006E65),
    onTertiaryContainer = Color(0xFF84F0E2),
    background = Color(0xFFFAF8FF),
    onBackground = Color(0xFF131B2E),
    surface = Color(0xFFFAF8FF),
    onSurface = Color(0xFF131B2E),
    surfaceVariant = Color(0xFFDAE2FD),
    onSurfaceVariant = Color(0xFF434654),
    surfaceTint = Color(0xFF1353D8),
    inverseSurface = Color(0xFF283044),
    inverseOnSurface = Color(0xFFEEF0FF),
    outline = Color(0xFF737686),
    outlineVariant = Color(0xFFC3C5D7),
    error = Color(0xFFBA1A1A),
    onError = Color.White,
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    surfaceDim = Color(0xFFD2D9F4),
    surfaceBright = Color(0xFFFAF8FF),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF2F3FF),
    surfaceContainer = Color(0xFFEAEDFF),
    surfaceContainerHigh = Color(0xFFE2E7FF),
    surfaceContainerHighest = Color(0xFFDAE2FD),
)

// The references contain light screens only; this is the native dark extension.
internal val ToolboxDarkColors = darkColorScheme(
    primary = Color(0xFFB5C4FF),
    onPrimary = Color(0xFF002B7F),
    primaryContainer = Color(0xFF003FB1),
    onPrimaryContainer = Color(0xFFDBE1FF),
    inversePrimary = Color(0xFF003FB1),
    secondary = Color(0xFFB9C7DF),
    onSecondary = Color(0xFF233145),
    secondaryContainer = Color(0xFF3A485B),
    onSecondaryContainer = Color(0xFFD5E3FC),
    tertiary = Color(0xFF6BD8CB),
    onTertiary = Color(0xFF003730),
    tertiaryContainer = Color(0xFF005049),
    onTertiaryContainer = Color(0xFF89F5E7),
    background = Color(0xFF10131B),
    onBackground = Color(0xFFE2E7FF),
    surface = Color(0xFF10131B),
    onSurface = Color(0xFFE2E7FF),
    surfaceVariant = Color(0xFF434654),
    onSurfaceVariant = Color(0xFFC3C5D7),
    surfaceTint = Color(0xFFB5C4FF),
    inverseSurface = Color(0xFFE2E7FF),
    inverseOnSurface = Color(0xFF283044),
    outline = Color(0xFF8D90A1),
    outlineVariant = Color(0xFF434654),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    surfaceDim = Color(0xFF10131B),
    surfaceBright = Color(0xFF363943),
    surfaceContainerLowest = Color(0xFF0B0E16),
    surfaceContainerLow = Color(0xFF181C26),
    surfaceContainer = Color(0xFF1E222D),
    surfaceContainerHigh = Color(0xFF282C37),
    surfaceContainerHighest = Color(0xFF333743),
)
