package com.cangshuo.toolbox.feature.webtools.domain

import java.util.Base64

class WebToolExportException : Exception("Web export unavailable", null)

data class WebToolExport(val mimeType: String, val fileName: String, val bytes: ByteArray)

fun interface WebToolExportRepository {
    suspend fun save(destination: String, export: WebToolExport)
}

class SaveWebToolExportUseCase(private val repository: WebToolExportRepository) {
    suspend operator fun invoke(destination: String, export: WebToolExport) = repository.save(destination, export)
}

/** Only bounded image exports generated by the official page, without a JavaScript interface. */
object DecodeWebToolExportUseCase {
    const val MAX_BYTES = 4_000_000
    const val MAX_URL_CHARS = 5_333_400

    operator fun invoke(dataUrl: String): WebToolExport {
        try {
            if (dataUrl.length > MAX_URL_CHARS) throw WebToolExportException()
            val separator = dataUrl.indexOf(',')
            if (separator !in 1..64) throw WebToolExportException()
            val (mime, name) = when (dataUrl.substring(0, separator)) {
                "data:image/png;base64" -> "image/png" to "qrcode.png"
                "data:image/jpeg;base64" -> "image/jpeg" to "qrcode.jpg"
                "data:image/svg+xml;base64" -> "image/svg+xml" to "qrcode.svg"
                else -> throw WebToolExportException()
            }
            val bytes = Base64.getDecoder().decode(dataUrl.substring(separator + 1))
            if (bytes.isEmpty() || bytes.size > MAX_BYTES) throw WebToolExportException()
            val valid = when (mime) {
                "image/png" -> bytes.size >= 24 && bytes.take(8) == listOf(137, 80, 78, 71, 13, 10, 26, 10).map(Int::toByte) &&
                    dimension(bytes, 16) in 1..2048 && dimension(bytes, 20) in 1..2048
                "image/jpeg" -> bytes.size >= 4 && bytes[0] == 0xff.toByte() && bytes[1] == 0xd8.toByte() &&
                    bytes[bytes.lastIndex - 1] == 0xff.toByte() && bytes.last() == 0xd9.toByte()
                else -> safeSvg(bytes)
            }
            if (!valid) throw WebToolExportException()
            return WebToolExport(mime, name, bytes)
        } catch (_: Exception) {
            throw WebToolExportException()
        }
    }

    private fun dimension(bytes: ByteArray, offset: Int): Long = (offset..offset + 3).fold(0L) { n, i ->
        (n shl 8) or (bytes[i].toInt() and 255).toLong()
    }

    // Fixed geometry-only template. Reject scripts, links, entities, styles and embedded resources.
    private fun safeSvg(bytes: ByteArray): Boolean {
        if (bytes.any { it.toInt() !in 32..126 }) return false
        val text = bytes.toString(Charsets.US_ASCII)
        val pattern = Regex("""<svg xmlns="http://www.w3.org/2000/svg" width="([0-9]{1,4})" height="\1" viewBox="0 0 \1 \1"><rect width="\1" height="\1" fill="#FFFFFF"/><path d="[M0-9 h vz-]+" fill="#000000"/></svg>""")
        val match = pattern.matchEntire(text) ?: return false
        return match.groupValues[1].toInt() in 1..2048
    }
}
